name: Run tests

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.1
      - name: install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test || true

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.1
      - name: Ensure execute permission for c8
        run: chmod +x ./node_modules/.bin/c8
      - name: calculate test coverage
        run: ./node_modules/.bin/c8 --all --report-dir=./coverage --reporter=lcov --exclude=./src/.internal mocha 
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
